### PR TITLE
Ensures the process exits with non-zero status even if logging is turned off.

### LINKED ISSUE #32: Continues on error when `silent` option passed to Output class instance
https://github.com/justkey007/tsc-alias/blob/19356e75d45e32a1a97aff524829ec4c90c88a16/src/utils/output.ts#L11-L14

It looks like the intention of the `silent` option is to disable console logging. However, in the case of calling `output.error` when that value is set, the early return prevents the process from being ended.

For example, in the entrypoint file using silent mode would allow the following validity checks to fail while the program continues running:

https://github.com/justkey007/tsc-alias/blob/19356e75d45e32a1a97aff524829ec4c90c88a16/src/index.ts#L61-L69

### PR DESCRIPTION
**Pull request by adam-coster**
Fixes #32

Additionally adds minor refactor of entrypoint to convert validator code into single-line assertions.

(Note that I originally wanted to have the assertion be part of the `Output` class, but Typescript gets weird about class methods used as assertion functions.)

### CODE REVIEW

File: src/utils/output.ts [hunk 1]
```diff
@@ -3,14 +3,25 @@ import { Output as Console } from '@jfonx/console-utils';
...
     if (this.silent) return;
     Console.info(message);
   }
 
-  error(message: string, exitProces = false) {
-    if (this.silent) return;
-    Console.error(message, exitProces);
+  error(message: string, exitProcess = false) {
+    if (!this.silent) {
+      Console.error(message);
```
Comment (adam-coster) [inline src/utils/output.ts:20]: The `Console.error` method does take an optional 2nd arg for whether or not to exit, which is what was previously being used. However, in that case the method exits using `process.exit()` without passing an argument, which defaults to `0`. The result is then that an error will cause a "SUCCESS" exit instead of a non-zero ERROR exit, which could cause pipelines to succeed when they shouldn't.
